### ISSUE TITLE
Ошибка если пустое поле

### ISSUE THREAD

**Issue by fessdmks** [NekruzRabiev/taskcsv#8]
1,"Goroka Airport","Goroka","Papua New Guinea","GKA2","AYGA",-6.081689834590001,145.391998291,5282,10,"U","Pacific/Port_Moresby","airport",""

такая строка не показывается на главной странице без фильтров

**Comment by fessdmks** [comment]
точнее какая то непонятная дичь, она иногда показывается - иногда нет. не могу зафиксировать ошибку. иногда пропадает строка 
2,"Madang Airport","Madang","Papua New Guinea","GKa1","AYMD",-5.20707988739,145.789001465,20,10,"U","Pacific/Port_Moresby","","OurAirports" с пустым предпоследним полем

**Comment by rab1ev** [comment]
Исправил
